spring.application.name=demo
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=root
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto =update
spring.security.user.name=123
spring.security.user.password=123
spring.security.jwt.secret=hC0MjDKz5OSyj8CgSq60OAorzkPr3V9hl3EdEerxAWfWM19n7hMuhsFkCrtFRGKudd2EQ4pIN0vhBx9JvPDdib
spring.security.jwt.expiration=3600000