spring.application.name=demo
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=root
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto =update
spring.security.user.name=123
spring.security.user.password=123
spring.security.jwt.secret=hC0MjDKz5OSyj8CgSq60OAorzkPr3V9hl3EdEerxAWfWM19n7hMuhsFkCrtFRGKudd2EQ4pIN0vhBx9JvPDdib
spring.security.jwt.expiration=3600000
spring.jackson.naming-strategy=SNAKE_CASE
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Github Oauth
#spring.security.oauth2.client.registration.github.client-id=Iv1.9c8b0e5a7c3d4b8
#spring.security.oauth2.client.registration.github.client-secret=0c8b1e5a9c8d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8